### ISSUE TITLE
[The Mr Incredible] <You can jump in the air with the shield> If you make mr incredible shield wide, you can kinda jump in the air if you spam the jump button.  1. Place and make the incredible shield very wide.  2. Grab it in play mode and jump off an edge.  3. spam the jump button.  (doesnt always work) You can Try on the map 7ce-89e-4ab. 

### ISSUE THREAD

**Issue by Hacky1904** [EthanSK/Ye-Olde-Meme-Game-2-Alpha#10]
![Bilde_2022-12-08_192837326](https://user-images.githubusercontent.com/108363641/206536802-dae4f629-f0c7-4c45-8a7b-fd1f08db76ac.png)
**Describe the bug**
What is the bug

**To Reproduce**

**Expected behavior**
What you expected to happen.

**Screenshots**
If possible, add screenshots to help explain the problem.

**Desktop (please complete the following information):**
 - Operating System: [e.g. MacOS 12.6, Windows 11]

**Additional context**

**Comment by EthanSK** [comment]
Do you mean when the head touches the floor you can jump? coz that's expected behaviour. Also this is an experimental mode feature, so it's not fully supported, there will be untested bugs in experimental mode :)

**Comment by Hacky1904** [comment]
No when you are literally in the air and should fall down, you can spam the jump button to jump in the air with the wide shield

**Comment by EthanSK** [comment]
fixed
