### ISSUE TITLE
[BUG] Leaderboard shows wrong display name

### ISSUE THREAD

**Issue by QFSW** [EthanSK/Ye-Olde-Meme-Game-2-Alpha#12]
**Describe the bug**
I set my display name to QFSW then played a level and the leaderboard shows my default autogen display name
![image](https://user-images.githubusercontent.com/11485449/208249096-b04ffb2c-5004-4c13-80c8-47c8f8cc925b.png)

**Expected behavior**
Shows QFSW

**Screenshots**
If possible, add screenshots to help explain the problem.

**Desktop (please complete the following information):**
 - Windows 11

**Comment by EthanSK** [comment]
it takes like 10 mins for  it to update, is it still there?

**Comment by QFSW** [comment]
@EthanSK could you perhaps locally check if the id of the user is the local user's id then override the display name with their local representation? You'd still have "lag" for other players display names but I think your local display name will be by far the most noticeable (since starting the game, setting your name then playing a level is probably a common flow) and should be work aroundable locally?

**Comment by EthanSK** [comment]
that's smart
