### ISSUE TITLE
[FEATURE] <Fps Limit Setting>

### ISSUE THREAD

**Issue by Defaultbenjys** [EthanSK/Ye-Olde-Meme-Game-2-Alpha#16]
A fps Limit setting would help a ton since now it does not look to have any limit.

**Comment by EthanSK** [comment]
is this important?

**Comment by EthanSK** [comment]
added in upcoming version 0.6

![image](https://user-images.githubusercontent.com/13756744/221074008-c16f3922-d675-4672-9ef6-37840da310f5.png)

**Comment by EthanSK** [comment]
> is this important?

pontypants video made me realize it was important haha https://www.youtube.com/watch?v=KOnr0FSDHH8
