### ISSUE TITLE
[The lava kinda glitched] <Gliched lava when many memoragmen>

### ISSUE THREAD

**Issue by Hacky1904** [EthanSK/Ye-Olde-Meme-Game-2-Alpha#17]
The bug is When you are many duplicate memoragmen and you go onto the lava, if you keep moving you dont really take damage all the time.
(a03-d21-428)

To Reproduce you can go into the level above and go to the left and jump off, then when you have duplicated many times go off the dew and begin just walking across the lava floor, and remember to keep moving because you are more likely to take damage when you are standing still.

Whats expected to happen is that you wont really take damag if you keep walking.

**Screenshots**
(Dont know if the screenshot works, but if you need one im hacky, just like tell in discord or smth) ![Skjermbilde_20230208_180857](https://user-images.githubusercontent.com/108363641/217604563-2f50fc2b-932f-4d24-bd3d-8a83dcae121a.png)

**Desktop (please complete the following information):**
 - Operating System: [e.g. MacOS 12.6, Windows 11]
 
Some additional context is that i dont know how many duplicates there need to be but ye.

**Comment by EthanSK** [comment]
hmm, i can't seem to see an error

memeorang man only dies if he touches the lava

**Comment by Hacky1904** [comment]
oh sorry i think i misunderstood, so  the clones does not actually  take damage and so, if memorag man is on top of a clone he does therefore not take damage?

**Comment by EthanSK** [comment]
the damage doesn't propagate through the chain of memeorang mans no
