### ISSUE TITLE
[Edit But not make a copy doesnt work] <non copying edit level mode, not working>

### ISSUE THREAD

**Issue by Hacky1904** [EthanSK/Ye-Olde-Meme-Game-2-Alpha#18]
**Well i was updating my sandbox level with the fetaure that said edit but not make a copy, but it did make a copy and the old one is still in hall of fame. although if i go on my created levels i can only find one. so it seems like it only updates in "Your Created Leves"
*
 (The New One is f89-f15-447 and the old one is 3d2-4f8-499)

**To Reproduce u just go into the button level builder, your created levels, click on a level and click edit without making a copy. edit it and then see that puplicly it doesnt change, it only changes in your created levels.**

**Expected behavior**
What you expected to happen.

**![Skjermbilde_20230217_230024](https://user-images.githubusercontent.com/108363641/219802259-50534662-b043-4428-ad8a-f9e7dae105f3.png)
![Skjermbilde_20230217_230033](https://user-images.githubusercontent.com/108363641/219802276-65c4eb54-d76c-4724-943a-56a76c437394.png)
![Skjermbilde_20230217_230208](https://user-images.githubusercontent.com/108363641/219802292-cd6e8e96-2c49-4e04-9090-cf8acd047f96.png)**
If possible, add screenshots to help explain the problem.

**Desktop (please complete the following information):**
 - Operating System: [e.g. MacOS 12.6, Windows 11]

**May only take a few hours to actually update or mabey just wont show the same for others, idk**

**Comment by EthanSK** [comment]
this is intended behaviour 
<img width="860" alt="image" src="https://user-images.githubusercontent.com/13756744/220751406-f85c6fdd-09b1-41e0-ad8a-2fb7ee8afec2.png">
I can't allow ppl to edit levels they've already published, just upload the new version, and deprecate the old one, linking the new one while doing that
