### ISSUE TITLE
[BUG] Anti-cheat false detection. Possible crash?

### ISSUE THREAD

**Issue by imaloser71** [EthanSK/Ye-Olde-Meme-Game-2-Alpha#2]
**Describe the bug**
I attempted to play a noob level in meme game and when i completed it in speedrun time (not cheated 100 emoji but seriously) it told me it's cheated?? 
The game also closes a second after the pop-up which i dont know if its intentional or not since there is an X button on the modal.
I will provide video evidence soon.

**To Reproduce**
1. Go to 'Published Levels'
2. Find level `d40-7b8-4af`
3. Beat the game
4. See false detection along with large barrage of errors

**Expected behavior**
I expected to beat the level and be able to write a review. (Also, It seems that it still counted towards the play-count of the level)

**Screenshots**
[the fuck](https://cdn.discordapp.com/attachments/1048627891660918785/1048885752974553158/image.png)

**Desktop (please complete the following information):**
 - Operating System: Windows 10 Pro 21H2 (19044.2251)

**Comment by imaloser71** [comment]
[video footage of bullshittery](https://streamable.com/uhai0x)

**Comment by EthanSK** [comment]
will take a look

**Comment by EthanSK** [comment]
forgot to deploy latest server, sholud work fine now

**Comment by EthanSK** [comment]
still has issue, looking into it

**Comment by EthanSK** [comment]
should be fixed now in 0.2
