### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by StalefPee** [EthanSK/Ye-Olde-Meme-Game-2-Alpha#22]
**Describe the bug**
Im stuck step bro
**To Reproduce**
start game
**Expected behavior**
see main menu
![Screenshot 2024-05-10 152728](https://github.com/EthanSK/Ye-Olde-Meme-Game-2-Public/assets/169463021/2d521670-e091-4657-8b85-e08c703ad252)

**Screenshots**
If possible, add screenshots to help explain the problem.

**Desktop (please complete the following information):**
 - Operating System: , Windows 11

**Additional context**

**Comment by EthanSK** [comment]
we resolved in the discord vc
