### ISSUE TITLE
[BUG] <yeah so if you ride a forklift into a wall in some way you get noclipped to the other side ! ! ! >

### ISSUE THREAD

**Issue by iqup3g** [EthanSK/Ye-Olde-Meme-Game-2-Alpha#4]
**Describe the bug**
What is the bug

**To Reproduce**

**Expected behavior**
What you expected to happen.

**Screenshots**
If possible, add screenshots to help explain the problem.

**Desktop (please complete the following information):**
 - Operating System: [e.g. MacOS 12.6, Windows 11]

**Additional context**

**Comment by imaloser71** [comment]
why didnt yhouj fill out the reproduction!!! then we cant reproduce the bug. you should replace 'what is the bug' with the bug description and not the title, the title of the issue should be a consise and short title

**Comment by EthanSK** [comment]
@imaloser71  is right. 

but also, this is by design. there is no way to make a system to get out of the forklift without clipping, so it's up to you to design your level right
