### ISSUE TITLE
[BUG] Infinite likes

### ISSUE THREAD

**Issue by imaloser71** [EthanSK/Ye-Olde-Meme-Game-2-Alpha#5]
**Describe the bug**
You can get an infinite amount of likes by beating the level, pressing like/dislike, submitting it, then replaying it how many times you want likes.

**To Reproduce**
1. Play any level
2. Beat said level
3. Before submitting, press like/dislike [ON THE WIN SCREEN]
4. Replay said level
5. Return to menu
6. Gained 2 likes instead of keeping 1

**Expected behavior**
Not gaining additional likes after replaying (on the same account of course)

**Screenshots**
[bruh](https://cdn.discordapp.com/attachments/1007007244203868162/1048897786277539850/image.png)

**Desktop (please complete the following information):**
 - Operating System: Windows 10 Pro 21H2 (19044.2251)

**Additional context**
ur implementation sucks nosql sucks

**Comment by imaloser71** [comment]
Seems to be a temporary visual bug

**Comment by EthanSK** [comment]
yeah its just coz it updates locally
