### ISSUE TITLE
[The hitbox of spinning tom is very weird, the texture of tom can fall upside down through the ground while the like floating part is over the ground, so the tom hangs under the ground like a bat.] <Spinning tom is broken> 1. Place a ground that has an upwards slope to the right.  2. place 2 stones on the slope on top of eachother, almost like a wall. place the spinning tom on top of the stones and let it slide of to the left on the flat ground.

### ISSUE THREAD

**Issue by Hacky1904** [EthanSK/Ye-Olde-Meme-Game-2-Alpha#6]
**Describe the bug**
What is the bug

**To Reproduce**

**Expected behavior**
What you expected to happen.

**Screenshots**
If possible, add screenshots to help explain the problem.

**Desktop (please complete the following information):**
 - Operating System: [e.g. MacOS 12.6, Windows 11]

**Additional context**

**Comment by imaloser71** [comment]
does anyone looking at this github repo know whats a DESCRIPTION?!?!?! i am praying for reeethan to not go insane after reading these shits

**Comment by EthanSK** [comment]
lol 

i know what he's on about tho.

but tbh i think its fine, its kinda funny

**Comment by EthanSK** [comment]
i made his center of mass lower so it should be much less likely to stay flipped.
