### ISSUE TITLE
[FEATURE] Force update of older versions.

### ISSUE THREAD

**Issue by imaloser71** [EthanSK/Ye-Olde-Meme-Game-2-Alpha#8]
As it seems, the game seems to not have any "lock out older versions" mechanism. This could be quite bad, because future updates might break compatibility which normally shouldn't be a worry.
For example, you definetly have new memes planned, or what if you will have to change the format in the future?
I suggest storing the version somewhere in the game's files (maybe also use it to display the version in the bottom right of the main menu?) then, make the game send the version (as a HTTP request header or optionally a parameter stored somewhere in the body) when it wants to request something, like publishing a level or logging in among other things. Then, the latest version can be stored in the server and if the versions in the request and the server don't match, it could reject the request and send back a message saying something along the lines of "Update to latest version to use all of game's features." in the same format the server already sends back errors (since thats when v0.1 and v0.2 display errors as a modal). Finally, in the "after-this-gets-implemented" versions of the game, it should check by itself.

I believe it is _best_ to implement such a system _early on_, **The more versions you add, the more time it will take to lock the older versions out.**

**Comment by EthanSK** [comment]
added system to enforce a minimum version. Also, now you can't play levels that were made with a newer version of the game.
